apiVersion: v1
kind: Service
metadata:
  name: sonarqube
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000  # This should match the port on your SonarQube container
      nodePort: 30000  # Choose a port in the range 30000-32767
  selector:
    app: sonarqube
