apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-ci
  template:
    metadata:
      labels:
        app: jenkins-ci
    spec:
      containers:
      - name: jenkins-ci
        image: jenkins:2.32.2
        resources:
          limits:
            cpu: 1.0m
            memory: 256Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-ci-service
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: jenkins-ci
