apiVersion: v1
kind: PersistentVolume
metadata:
  name: ansible-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/ansible"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ansible-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
