---
- name: Install nginx
  hosts: all
  sudo: yes
  tasks:
    - name: Ensure python-apt is installed
      apt:
        name: python3-apt
        state: present
    - name: Ensure nginx is installed
      apt:
        name: nginx
        state: present
    - name: Start nginx service
      service:
        name: nginx
        state: started
