kubectl apply -f mongo-config.yaml
kubectl apply -f mongo-secret.yaml
kubectl apply -f mongo.yaml
kubectl apply -f webapp.yaml
kubectl get pods -A
kubectl apply -f jenkins-service.yaml
kubectl apply -f jenkins-nodeport.yaml
kubectl apply -f jenkins-deployment.yaml
kubectl apply -f multiple-pod.yaml
kubectl apply -f ingress-class.yaml
kubectl apply -f ingress.yaml
kubectl apply -f virtualmachine-crd.yaml
kubectl apply -f CRD.yaml