apiVersion: v1
kind: ReplicationController
metadata:
  name: example-replication-controller
spec:
  replicas: 3
  selector:
    app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-container
        image: nginx:latest
