apiVersion: v1
kind: Secret
metadata:
  name: sonarqube-db-secret
type: Opaque
data:
  SONARQUBE_JDBC_USERNAME: c29uYXI=   # base64 encoded value for 'sonar'
  SONARQUBE_JDBC_PASSWORD: c29uYXI=    # base64 encoded value for 'sonar'
